version: 2.1

jobs:
  build-and-test:  
    docker:
      - image: cimg/openjdk:11.0
    steps:
      - checkout
      - run:
          name: Build
          command: cd ./backend-spring-boot/air-quality && mvn -B -DskipTests clean package
      - run:
          name: Test
          command: cd ./backend-spring-boot/air-quality && mvn test

workflows:
  sample: 
    jobs:
      - build-and-test
