version: 2.1
orbs:
  node: circleci/node@4.3.0
jobs:
  build-and-test:  
    docker:
      - image: cimg/openjdk:11.0
    steps:
      - checkout
      - run:
          name: Build
          command: cd ./backend-spring-boot/air-quality && mvn -B -DskipTests clean package
      - run:
          name: Test
          command: cd ./backend-spring-boot/air-quality && mvn test
  build-node:
    executor: node/default
    steps:
      - checkout
      - run:
          name: Install
          command: cd ./frontend-react && npm clean install
      - run:
          name: Test
          command: cd ./frontend-react && npm run build

workflows:
  sample: 
    jobs:
      - build-and-test
      - build-node
